#!/usr/bin/env python3
"""Generate the BYTES-path byte -> character-class table.

Single auditable derivation, no hand-maintained table:

    byte -> GPT-2 byte-alphabet codepoint -> Unicode general category -> class

Classes are exactly the four the GPT-2 pattern needs: L, N, S (whitespace),
O (other). ASCII is handled separately and is NOT part of this table, because
0x20 is whitespace by virtue of being the ASCII space byte even though its
byte-alphabet symbol U+0120 is a letter.

Output is a C header consumed by gt_pretok.c.
"""
import sys, unicodedata

def bytes_to_unicode():
    bs = list(range(0x21, 0x7f)) + list(range(0xa1, 0xad)) + list(range(0xae, 0x100))
    cs = bs[:]
    n = 0
    for b in range(256):
        if b not in bs:
            bs.append(b); cs.append(256 + n); n += 1
    return dict(zip(bs, [chr(c) for c in cs]))

B2U = bytes_to_unicode()

def category(cp):
    ch = chr(cp)
    if ch.isspace() or unicodedata.category(ch) in ("Zs", "Zl", "Zp", "Cc"):
        return "S"
    cat = unicodedata.category(ch)
    if cat[0] == "L": return "L"
    if cat[0] == "N": return "N"
    return "O"

CLS = "LNOS"
table = {}
for b in range(0x80, 0x100):
    cp = ord(B2U[b])
    table[b] = (cp, category(cp))

out = []
out.append("/* Generated by tools/gen_byteclass_table.py -- do not hand-edit.")
out.append(" *")
out.append(" * BYTES-path class of every NON-ASCII byte, derived as")
out.append(" *     byte -> GPT-2 byte-alphabet codepoint -> Unicode category")
out.append(" * and reduced to the four classes the GPT-2 pattern needs.")
out.append(" *")
out.append(" * ASCII (00..7F) is deliberately absent: it is handled directly, and")
out.append(" * 0x20 is whitespace as a BYTE even though its byte-alphabet symbol")
out.append(" * U+0120 is a letter. Generalising this table onto ASCII would be wrong.")
out.append(" */")
out.append("#ifndef GT_BYTE_CLASS_H")
out.append("#define GT_BYTE_CLASS_H")
out.append("")
out.append("#include <stdint.h>")
out.append("")
out.append("/* Byte-alphabet codepoint for each non-ASCII byte. */")
out.append("static const uint16_t GT_BYTE_ALPHABET_CP[128] = {")
row = ""
for i in range(0x80, 0x100):
    row += "0x%04X, " % table[i][0]
    if (i - 0x80) % 8 == 7:
        out.append("    " + row.rstrip()); row = ""
if row: out.append("    " + row.rstrip())
out.append("};")
out.append("")
out.append("/* Class: 'L' letter, 'N' number, 'S' whitespace, 'O' other. */")
out.append("static const char GT_BYTE_CLASS[129] = {")
row = ""
for i in range(0x80, 0x100):
    row += table[i][1]
    if (i - 0x80) % 32 == 31:
        out.append('    "%s" /* %02X..%02X */' % (row, i - 31, i)); row = ""
if row:
    out.append('    "%s" /* %02X..FF */' % (row, 0x100 - len(row)))
out.append("};")
out.append("")
out.append("#endif /* GT_BYTE_CLASS_H */")
open(sys.argv[1] if len(sys.argv) > 1 else "include/gt_byte_class.h", "w").write("\n".join(out) + "\n")

# report
import collections
print("80..BF classes:", collections.Counter(table[b][1] for b in range(0x80,0xC0)))
print("F5..FF classes:", collections.Counter(table[b][1] for b in range(0xF5,0x100)))
for b in range(0x80,0xC0,8):
    print("  %02X: %s" % (b, " ".join(f"{table[x][1]}(U+{table[x][0]:04X})" for x in range(b, b+8))))
