#!/usr/bin/env python3
"""Generate the byte -> byte-alphabet codepoint table.

Single auditable derivation: the three self-mapping runs
  0x21..0x7E, 0xA1..0xAC, 0xAE..0xFF
map to themselves; every other byte maps to 0x100 plus the count of
non-self bytes below it. This is GPT-2's bytes_to_unicode rule, and
gt_selftest verifies every entry against it.
"""
import sys


def itself(b):
    return (0x21 <= b <= 0x7E) or (0xA1 <= b <= 0xAC) or (b >= 0xAE)


out = []
out.append("/* Generated by tools/gen_bytemap_table.py -- do not hand-edit.")
out.append(" *")
out.append(" * byte -> GPT-2 byte-alphabet codepoint. The three self-mapping")
out.append(" * runs (0x21..0x7E, 0xA1..0xAC, 0xAE..0xFF) map to themselves;")
out.append(" * every other byte maps to 0x100 + (# non-self bytes below it).")
out.append(" */")
out.append("#ifndef GT_BYTE_TABLE_H")
out.append("#define GT_BYTE_TABLE_H")
out.append("")
out.append("#include <stdint.h>")
out.append("")
out.append("static const uint16_t GT_BYTE_TO_CP[256] = {")
row = ""
for b in range(256):
    if itself(b):
        v = b
    else:
        v = 0x100 + sum(1 for i in range(b) if not itself(i))
    row += "0x%03X, " % v
    if b % 8 == 7:
        out.append("    " + row.rstrip())
        row = ""
if row:
    out.append("    " + row.rstrip())
out.append("};")
out.append("")
out.append("#endif /* GT_BYTE_TABLE_H */")
open(sys.argv[1] if len(sys.argv) > 1 else "include/gt_byte_table.h", "w").write(
    "\n".join(out) + "\n"
)
